version: '2.3'

services:
#  devpi:
#    build:
#      context: .
#      dockerfile: Dockerfile-devpi
#    ports:
#      - "3141:3141"
#    volumes:
#      - .:/code

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - .:/code
#    depends_on:
#      - devpi
